services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data/

  odoo:
    image: odoo
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
    depends_on:
      - db  # Ensure the database starts before Odoo