networks:
  web-network:
    ipam:
      config:
        - subnet: 172.25.0.0/16

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    networks:
      web-network:
        ipv4_address: 172.25.0.10