version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Mount the current directory (containing 'app', Dockerfile, etc.)
# services:
#   front:
#     container_name: frontend
#     image: nginx:latest
#     ports:
#     - 8080:80
#     volumes:
#       - ./app:/usr/share/nginx/html:ro

